index: "snippets/commands/help.html"
template: "templates/doc.html"
commands:
  - "snippets/commands/run.html"
  - "snippets/commands/build.html"
  - "snippets/commands/docs.html"
  - "snippets/commands/share.html"
  - "snippets/commands/sync.html"
  - "snippets/commands/configure.html"
specs:
  - "snippets/specs/title.html"
  - "snippets/specs/run.html"
  - "snippets/specs/io.html"
  - "snippets/specs/args.html"
  - "snippets/specs/build.html"
  - "snippets/specs/data.html"
  - "snippets/specs/source.html"
  - "snippets/specs/papers.html"
